### PR TITLE
Generate code coverage when running unit tests.

### PR DESCRIPTION
**Pull request by koenedaele**
Shows what parts of your code are covered by unit tests and what parts aren't.

Currently this is being generated every time you run `npm run test`. If this is too much noise, I can change it so it only runs with a separate command, eg. `npm run test-with-coverage`.

Optionally, you can also add coveralls support so you get realtime updates on code coverage stats with every pull request.

### CODE REVIEW

**Comment by bkawk** [comment]
@koenedaele Could this be expanded to integrate with https://coveralls.io/ or similar?

**Comment by koenedaele** [comment]
@bkawk Yes, that's what I normally do (only done it for Python applications, but this should be similar). Makes it easier to track your code coverage through time.

**Comment by koenedaele** [comment]
@bkawk I can add the coveralls integration, but I would prefer a core developer creating the coveralls account.

**Comment by bkawk** [comment]
Sure I can make the coveralls account, this is great!

**Comment by bkawk** [comment]
@koenedaele I have sent you an email with the repo_token

**Comment by koenedaele** [comment]
@bkawk Should not be necessary. Repo tokens are only needed with private repositories.

**Pull request merged**
